#!/bin/csh -fx
#*****!/bin/csh -fx --- execute fast(f), show all commands(-x)*****
#

# Takes a .png file as input and outputs the QRcode contained within
# this file.  If the .png doesn't contain a QRcode an appropriate
# message is output to the command line.

#------------------------------------------------------------------------------
# History:
#
# 16Oct2016     Simone Magri    Original script
#
#------------------------------------------------------------------------------

# for testing
cd /lu1/smagri/uni/subj/proj30cp/imageMatching/qrCode

# for production
#cd /lu1/smagri/uni/subj/proj30cp/proj/ambulance


set qrcode = `zbarimg -q --raw hwTest.png`
set qrcode = `zbarimg -q --raw bad.png`
set qrcode = `zbarimg -q --raw bipolarKnob.png`


echo $qrcode

if ($qrcode == "") then
  echo "Error or no QRcode found."
else
  echo $qrcode
endif
